name: Build and Push to Private ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  setup-ecr:
    name: Setup ECR Repositories
    runs-on: ubuntu-latest
    environment: retail-shop
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create ECR repositories if they don't exist
        run: |
          # List of required ECR repositories
          REPOS=("retail-store-sample-cart" "retail-store-sample-catalog" "retail-store-sample-checkout" "retail-store-sample-orders" "retail-store-sample-ui" "retail-store-sample-utils")
          
          for repo in "${REPOS[@]}"; do
            echo "Checking if repository $repo exists..."
            
            # Check if repository exists
            if aws ecr describe-repositories --repository-names "$repo" --region ${{ secrets.AWS_REGION }} 2>/dev/null; then
              echo "Repository $repo already exists"
            else
              echo "Creating repository $repo..."
              aws ecr create-repository \
                --repository-name "$repo" \
                --region ${{ secrets.AWS_REGION }} \
                --image-scanning-configuration scanOnPush=true \
                --encryption-configuration encryptionType=AES256
              
              echo "Repository $repo created successfully"
            fi
          done

  build-and-push:
    name: Build and Push Services
    runs-on: ubuntu-latest
    environment: retail-shop
    needs: setup-ecr
    strategy:
      matrix:
        service: [cart, catalog, checkout, orders, ui]
        include:
          - service: cart
            dockerfile: src/cart/Dockerfile
            context: src/cart
          - service: catalog
            dockerfile: src/catalog/Dockerfile
            context: src/catalog
          - service: checkout
            dockerfile: src/checkout/Dockerfile
            context: src/checkout
          - service: orders
            dockerfile: src/orders/Dockerfile
            context: src/orders
          - service: ui
            dockerfile: src/ui/Dockerfile
            context: src/ui

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/retail-store-sample-${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Helm values with new image tag
        if: github.ref == 'refs/heads/main'
        run: |
          IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-7)
          ECR_REPO="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/retail-store-sample-${{ matrix.service }}"
          
          # Update the values.yaml file using yq for better YAML handling
          if command -v yq &> /dev/null; then
            # Use yq if available
            yq eval ".image.repository = \"$ECR_REPO\"" -i src/${{ matrix.service }}/chart/values.yaml
            yq eval ".image.tag = \"$IMAGE_TAG\"" -i src/${{ matrix.service }}/chart/values.yaml
          else
            # Fallback to sed with more specific patterns
            sed -i "s|repository: \${AWS_ACCOUNT_ID}\.dkr\.ecr\.\${AWS_REGION}\.amazonaws\.com/retail-[a-z]*|repository: $ECR_REPO|" src/${{ matrix.service }}/chart/values.yaml
            sed -i "s|tag: \".*\"|tag: \"$IMAGE_TAG\"|" src/${{ matrix.service }}/chart/values.yaml
          fi
          
          echo "Updated ${{ matrix.service }} image to $IMAGE_TAG"
          echo "ECR Repository: $ECR_REPO"
          echo "Image Tag: $IMAGE_TAG"
          
          # Create a summary file for manual review
          echo "## ${{ matrix.service }} Image Update" >> image-updates.md
          echo "- Repository: $ECR_REPO" >> image-updates.md
          echo "- Tag: $IMAGE_TAG" >> image-updates.md
          echo "- Commit: ${{ github.sha }}" >> image-updates.md
          echo "" >> image-updates.md

      - name: Upload image updates summary
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: image-updates-${{ matrix.service }}
          path: image-updates.md

  trigger-helm-update:
    name: Trigger Helm Values Update
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main' && always()
    steps:
      - name: Trigger Helm Values Update Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"helm-values-update"}'
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

 