name: Security Scan (Simple)

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allow manual triggering
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual trigger'

permissions:
  contents: read
  security-events: write

jobs:
  filesystem-scan:
    name: Filesystem Security Scan
    runs-on: ubuntu-latest
    environment: retail-shop
    timeout-minutes: 20
    strategy:
      matrix:
        service: [cart, catalog, checkout, orders, ui]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'src/${{ matrix.service }}'
          format: 'sarif'
          output: 'trivy-fs-results-${{ matrix.service }}.sarif'
          exit-code: '0'  # Don't fail the build, just report
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          skip-dirs: '**/node_modules/**,**/vendor/**'

      - name: Upload filesystem scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-fs-results-${{ matrix.service }}.sarif'
          category: 'trivy-fs-${{ matrix.service }}'

      - name: Generate scan summary
        if: always()
        run: |
          echo "## Security Scan Summary for ${{ matrix.service }}" >> scan-summary.md
          echo "- Service: ${{ matrix.service }}" >> scan-summary.md
          echo "- Scan Type: Filesystem" >> scan-summary.md
          echo "- Scan Date: $(date)" >> scan-summary.md
          
          if [ -f "trivy-fs-results-${{ matrix.service }}.sarif" ]; then
            echo "- Filesystem Scan Status: COMPLETED" >> scan-summary.md
          else
            echo "- Filesystem Scan Status: FAILED" >> scan-summary.md
          fi
          
          echo "" >> scan-summary.md

      - name: Upload scan summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-summary-${{ matrix.service }}
          path: scan-summary.md